# fix color support
set-option -sa terminal-overrides ",xterm*:Tc"

# replace ctl-b with ctl-Space
set-option -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

# clear terminal
bind-key C-l send-keys C-l

# reload config file shortcut
unbind r
bind r source-file ~/.tmux.conf \; display-message "Reloaded tmux config."

# enable mouse
set -g mouse on

# index windows and panes starting at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# split panes using | and -
bind \\ split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind '%'

# swap windows
bind -r "<" swap-window -t -1
bind -r ">" swap-window -t +1

# keep current path on new window
bind c new-window -c '#{pane_current_path}'

# space to go to previous window
bind-key Space last-window

# alt h/l to switch window
bind -n M-H previous-window
bind -n M-L next-window

# capital X to kill window (with confirmation)
# bind -n X confirm-before kill-window
bind-key X confirm-before kill-window

# alt shift h/l/k/j to resize pane
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-H resize-pane -L 5
bind -n M-L resize-pane -R 5

# alt arrow keys to move panes
bind -n M-Left swap-pane -D
bind -n M-Right swap-pane -U

# # theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'


run '~/.tmux/plugins/tpm/tpm'
